apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ccc 
  janus-idp.io/tekton: ccc
  backstage.io/kubernetes-id: ccc
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ccc
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  