apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ccc
  janus-idp.io/tekton: ccc
  backstage.io/kubernetes-id: ccc
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ccc
resources:
- deployment.yaml
- route.yaml
- service.yaml
